README.md
cmd/scan.go
core/common.go
core/git.go

From https://github.com/JetBrains/Qodana/discussions/96: we need a mode to checkout the repository to and then run Qodana with --changes inside it.
For CLI the commit could be selected manually, but for GitHub action / others we'll get the variables from the environment / service.
Two cases when using the new option:
- Used locally 
- Revert to the base commit with all changes kept (== soft reset), 
- Run analysis
- Abort revert 
- Used in CI 
- Revert to the base commit with all changes kept (== soft reset), 
- Run analysis
P.S. Used in CI use-case: commit begins with `CI` – special prefix for CI extensions, no way to mess it with any other commit random SHA256, because SHA256 can't contain `I` symbol, did it to skip adding yet another option to the pile of options for skipping revert …

:zap: Add `--commit` scan option

---

cmd/cmd_test.go
cmd/pull.go
cmd/root.go
cmd/scan.go
core/container.go
core/system.go

These changes introduce experimental Podman support.
Thanks to Podman providing Docker API support, almost no significant changes are required from our side.
But I had to change our basic host checks logic before the Qodana container started:
- do not rely on `docker` in `$PATH`
- make sure we are mounting the correct directories with the correct permissions
- remove Docker from my machine and try using Podman instead (that took the most time) 😃
- https://github.com/JetBrains/Qodana/discussions/144
- https://youtrack.jetbrains.com/issue/QD-4729/Support-Podman
Only some Qodana users want to install Docker but have Podman installed and configured on their machine and agents, that is why we need to address it.
- removed Docker from my machine completely
- installed Podman
- configured Podman …

:zap: Introduce experimental `podman` support

---

core/ci.go
core/container.go

Always forward `QODANA_BRANCH`, `QODANA_REMOTE_URL`, and `QODANA_REVISION` when they are available.
https://youtrack.jetbrains.com/issue/QD-5021
This way we always make sure that regardless of what actions are performed with the repository we always have the needed data when it's available in the environment
I Ran the GitHub actions test suite in this repository, the variables can be seen in the log output with the enabled debug.

:bug: Always forward environment context about Git when it's available

---

cmd/cmd_test.go
core/ide.go

Take into the consideration plugins that should be installed and don't ignore them.

:bug: Don't run exclude plugins logic in container, since it was already computed

---

core/ide.go

- @KoT9R bundled the publisher to the linters starting from 2023.3
- CLI is being run as an entrypoint in all of the latest 2023.3 images
- Once the publisher is bundled to the latest installers, this pull request should be merged
- Note: this functionality will be removed after 2023.3 release and CLI switch to 2023.3 version.
https://youtrack.jetbrains.com/issue/QD-5059/

:bug: Do not run the publisher twice for container

---

.mailmap
cmd/cmd_test.go
cmd/scan.go
core/core_test.go
core/ide.go
core/options.go

Removes the `--stub-profile` flag from generated application args, remove default `profile.xml` argument too.
The flag is considered legacy and is being removed from Qodana. If users still supply the flag, a notice is logged.
On a side note, it's my first time writing golang, so I'm happy for any pointers. :)
Ran qodana locally.
It's a deprecation.

:wastebasket: Deprecate `stub-profile` flag (QD-6638)

---

core/options.go
core/properties.go

Lost during migration from endpoint.

:bug: Docker container should support /data/coverage as coverage directory.

---

core/core_test.go
core/properties.go
core/yaml.go

By default in container we will disable .NET Framework completely.

:children_crossing: Add possibility to set TFMs for qodana-dotnet.

---

core/core_test.go
core/properties.go

- in qodana we don't open project via activities, flag must be enabled when we would want to do that
- see in intellij f036cf057bed40c54545826909e27f090667af06 com.jetbrains.python.sdk.PythonSdkUpdater#dropUpdaterInHeadless

QD-7787 Disable project opening via activities flag

---

cmd/init.go
cmd/scan.go
core/common.go
core/common_test.go
core/configurator.go
core/installers.go
core/installers_test.go
core/native.go
core/options.go
core/output.go
core/system.go
core/yaml.go

PR is based on @tiulpin change https://github.com/JetBrains/qodana-cli/commit/585cd66b3abf1a1d11ad6feb4a943216728b1ec3 here

:children_crossing: Refactor the way we select linters.

---

core/contributors.go
core/contributors_test.go
core/git.go

by @taport, but with a cherry-pick to a proper branch
Changes made to align with contributor counting in qodana cloud:
- Stop using mailmap
- Always ignore qodana bot when counting contributors
- Count contributors by unique (email + username)
Closes #243

:recycle: Align contributor counting with qodana cloud

---

core/core_test.go
core/env.go

The variable is already read by the IDE [here](https://jetbrains.team/p/ij/repositories/ultimate/files/51ed2191ad83f9aad4acd194d0b103332e8e0b35/plugins/qodana/core/src/org/jetbrains/qodana/staticAnalysis/sarif/GitReportContributor.kt?tab=source&line=46&lines-count=1), but never set anywhere.
This is sadly not bulletproof, as the repo URLs might use ssh. In that case I think it's better to warn the user to explicitly provide the value, instead of trying some replacement magic on the ssh url.
Unit test only. Worked through the docs of the various CI environments to see if there are other options then omitting the `.git` suffix, sadly that's only for gitlab. Also cross referenced https://github.com/cucumber/ci-environment/blob/main/CiEnvironments.json

:sparkles: [QD-8082] Set QODANA_REPO_URL variable

---

core/core_test.go
core/properties.go

This is the cause for the current issues in IJ runs. Tests fail because the JDK was not configured correctly, which is not completely true - the mechanism tries to resolve `java.lang.Object`, but this fails because indexes are not yet ready. Thus the JDK is treated as invalid.

Temporarily disable scanning in smart mode

---

core/core_test.go
core/ide.go
core/properties.go
core/system.go
linter/run.go
platform/argflags.go
platform/git.go
platform/options.go
platform/yaml.go

See QD-8139 - a new of running qodana on a diff of files. When passed the args ` --diff-start` and `--diff-end`, cli will checkout the respective commits, run bootstrap and the linter. In the first run, we don't apply fixes or show results, but use the report as baseline for the second run.
I'm still thinking about making these inner bootstraps a separate config property. Probably we also want to run the first one as defined by in the commit of `--diff-start` and the second one by `--diff-end`. Also need to look into testing still

:sparkles: Add new way running qodana on a diff

---

core/system.go

Log dir implicitly depends on results dir, which we change for each run. Only caught this when running on a new project, else the directories existed before

:bug: Prepare directories for each diff run

---

core/ide.go
core/run_scenario.go
core/run_scenario_test.go
core/system.go
platform/argflags.go
platform/git.go
platform/options.go

As outlined in slack:
- Make `--commit` an alias of `--diff-start`
- Default `--diff-end` to `git rev-parse HEAD`
- Add a new flag `--force-incremental-script`
- Prefer scoped script for .NET, old local changes for everything else
I did not go and deprecate `--commit`, because it turns out to be quite a hassle: For every combination of cli and linter, we'd need to figure out what to pass to avoid deprecation notices and ensure compatibility

:sparkles: Prefer 'scoped' over 'local-changes' in .NET

---

cloud/license.go
cmd/init.go
core/ide.go
platform/common.go
platform/options.go
platform/run.go
platform/token.go

This PR addresses https://youtrack.jetbrains.com/issue/QD-8272/
We would filter out incompatible linters based on the license plan if the token was provided.
If the token is not provided, the behavior will be the same. 
- We do not try/ask users to explicitly provide the token so as not to break the UX that was before. But if the token was provided, we will do an additional check on the linters selection and won't suggest incompatible products
- I want this to change as minimal as possible, without massive refactorings just before the release, so the proposed solution is not the best one possible, but is about keeping as less things touched as possible
https://youtrack.jetbrains.com/issue/QD-8272/

:zap: Filter out non-supported linters by license plan (QD-8272)

---

core/system.go

Well, we did update how we set version, but we left `v` inside the update check..
```bash
qodana --version
qodana version 2024.1.1
!  New version of qodana CLI is available: v2024.1.1. See https://jb.gg/qodana-cli/update
!  New version of qodana CLI is available: v2024.1.1. See https://jb.gg/qodana-cli/update
```

:bug: Fix check for updates versioning

---

cmd/init.go
platform/common.go
platform/options.go

We write `qodana.yaml` when running various commands. 
It's wrong when it's working in various scenarios that are not `init` subcommand.
For example, when users have quick fixes enabled, we would try to commit the newly produced file when users do not expect it.

:bug: Do not write `qodana.yaml` when not using `init` command

---

core/ide.go
core/run_scenario.go
core/run_scenario_test.go
platform/argflags.go
platform/options.go

:zap: QD-9730 Switch to scoped script for incremental analysis.

---

README.md

Minor update of documentation
- [] My change requires a change to the [documentation](https://jetbrains.com/help/qodana).

:memo: Update documentation to use QODANA_ENDPOINT

---

cdnet/options_test.go
core/container.go
core/core_test.go
core/corescan/create_context.go
core/ide.go
core/startup/prepare.go
core/startup/xml.go
platform/commoncontext/compute.go
platform/qdcontainer/container.go

https://youtrack.jetbrains.com/issue/QD-10890/report-dir-doesnt-save-the-report-directory
Fix setting the report dir for the container runs by mounting it to a specific default container path, as we allowed setting this option in CLI before and it was not effective.
https://youtrack.jetbrains.com/issue/QD-10890/
```
QODANA_TOKEN=... go run cli/main.go scan --report-dir here --log-level debug
```

:bug: Fix setting `--report-dir` for container runs (QD-10890)

---

.github/workflows/post-release.yml

Added `permissions` to the `.github/workflows/post-release.yml` file to comply with GitHub Advanced Security best practices. This resolves a CodeQL finding which highlighted the lack of explicit permission declarations in the workflow.
Fixes: *[insert issue link or number]*  
Issue: **`post-release.yml` is missing permissions.**
GitHub Actions workflows that do not define permissions inherit repository-level defaults, which may include write access. This violates the principle of least privilege and may introduce unintended security risks. Adding explicit permissions ensures that the workflow only has access to what it needs.
Added the following block to `.github/workflows/post-release.yml`:
```yaml
permissions:
contents: write
pull-requests: write
packages: read
```
No code logic was …

QD-11641: GitHub workflow yml file is missing permissions
