- core/configurator.go
Do not merge before the release.
> ✨ New linters

- cmd/cmd_test.go
- core/configurator.go
Update the linters to the latest version
Runned project tests and checked how it performs locally and on GitHub actions
> :zap: Update to Qodana `2022.3` linters

- cmd/cmd_test.go
- core/installers.go
- core/installers_test.go
- core/product_info.go
- core/releases.go
- core/releases_test.go
- core/system.go
Description: to be added
Functionality: to be tested :)
> :zap: Obtain IDEs for local runs from feed. Allow obtaining EAP IDEs easier

- core/installers_test.go
- core/properties.go
Description: to be added
Functionality: to be tested :)
> :bug: Don't supply empty coverage directory.

- core/env.go
- core/ide.go
- core/license.go
- core/license_test.go
- core/properties.go
https://youtrack.jetbrains.com/issue/QD-6872
> QD-6872 Implement using QODANA_LICENSE_ONLY_TOKEN env.

- .github/workflows/ci.yml
- .github/workflows/release.yml
- cmd/cmd_test.go
- core/installers.go
- core/output.go
- go.mod
- go.sum
- run
> :arrow_up: Bump Go version and dependencies

- cloud/cloud.go
> :bug: pass response error correctly (QD-8046)

- core/contributors.go
- core/contributors_test.go
> :bug: Revert some changes to contributor counting

- platform/git.go
Align CLI with cloud
Test would be nice, but not easy to do deterministically, would have to create some dummy test repo, probably overkill for this change
> :recycle: Add --all flag to git log

- cli/go.mod
- cli/go.sum
- cmd/init.go
- cmd/pull.go
- cmd/send.go
- cmd/show.go
- core/ide.go
- platform/argflags.go
- platform/options.go
https://youtrack.jetbrains.com/issue/QD-2945
> :zap: Support custom path for `qodana.yaml` (QD-2945)

- core/system.go
> :bug: run converter if `show-report` or `save-report` are specified

- core/go.mod
- core/go.sum
- core/ide.go
> :bug: QD-8538 Sync jdk.table.xml with cache

- .github/qodana.sarif.json
- cmd/cmd_test.go
- platform/yaml.go
Small PR with updates for the baseline and a bug fix for a simple `scan` without additional options
Because the CMD test subsystem is already "complex," I've decided to change one complex test we already have.
> Fix running with an empty config

- cmd/cmd_test.go
- platform/configurator.go
https://jetbrains.slack.com/archives/C02D151MMSP/p1710934593418479
> :zap: Change the preferred default linter order

- platform/env.go
- platform/env_test.go
https://youtrack.jetbrains.com/issue/QD-7084#comment=27-9221277
> :bug: Use `GITHUB_REF_NAME` for GitHub branches (QD-7084)

- cmd/cmd_test.go
- platform/options.go
https://youtrack.jetbrains.com/issue/QD-8699/Marshal-open-.-is-a-directory
> :bug: Missing default `qodana.yaml` when running `scan` (QD-8699)

- platform/ext_gitlab.go
- platform/ext_test.go
https://youtrack.jetbrains.com/issue/QD-8925/Qodana-crashes-on-before-exit#focus=Comments-27-9792325.0-0
> :bug: Fix SARIF processing (QD-8925)

- core/core_test.go
- core/ide.go
- core/product_info.go
> QD-9205 Replace "inspect qodana" with "qodana" in launch arguments

- core/core_test.go
> :bug:Fix wrong test and change setting env in tests

- core/go.mod
- core/go.sum
- core/product_info.go
> :bug: Fix checking of is product in EAP for rider

- core/ide.go
- core/run_scenario.go
- core/run_scenario_test.go
- platform/argflags.go
- platform/options.go
> :zap: QD-9730 Switch to scoped script for incremental analysis.

- cmd/cmd_test.go
- core/installers.go
- core/installers_test.go
- platform/common.go
- platform/configurator.go
Review, but note: all native EAP distributions need to be republished
> :bug: Fix native macOS mode (QD-9694)

- core/core_test.go
- core/ide.go
Previously, no specific handling was implemented for symlinks (given the assumption that `.idea` would not contain any). This led to potential failures in the process for various reasons. These issues have now been resolved.
- Errors are now logged and returned by the method
- The analysis no longer fails if the copying process encounters an error
- Symlink handling is set to `cp.Skip` (as symlinked files are not relevant for the analysis)
https://youtrack.jetbrains.com/issue/QD-9927/2024.2.2-Failed-to-prepare-diff-run-nothing-to-compare-between-commit-and-commit#focus=Comments-27-10685633.0-0
> :bug: Handle errors for `.idea` cache and add logging (QD-9927)

- platform/sarif.go
https://github.com/JetBrains/qodana-cli/pull/464
> QD-10038 fix null in github report

- core/system.go
> :bug:QD-10360 Fix an order of setting variables custom JVM properties

- core/system.go
> :bug:QD-10419 Set up plugins once even in scoped script

- tooling/config_loader_cli.go
> :memo: Add doc on how to obtain config-loader-cli.jar

- .devcontainer/Dockerfile
- .github/workflows/ci.yml
- .github/workflows/devcontainer.yml
- go.work.github
> Use more GitHub Actions

- core/corescan/context_changes.go
- core/startup/prepare.go
- core/system.go
> :bug:QD-10274 Stop modifying unnecessary files in native mode

- .gitignore
- platform/sarifVersioning.go
- platform/sarifVersioning_test.go
https://youtrack.jetbrains.com/issue/QD-10662
> :bug: QD-10662: qodana-cli incorrectly retrieves current branch name

- core/startup/prepare.go
> :bug: QD-11375 Python: sync jdk.table.xml with python environment

- cloud/cloud.go
- cloud/cloud_test.go
- cloud/endpoints.go
- cloud/endpoints_test.go
- cloud/license.go
- cloud/versions.go
- core/startup/license.go
- platform/tokenloader/token_loader.go
> :bug: QD-11482 Support user defined protocol

- cmd/cmd_test.go
- core/startup/installers_test.go
- core/startup/releases_test.go
- platform/product/product.go
> :zap: QD-11553 Bump Qodana CLI to 2025.1 linters, 251 is released

- platform/product/product.go
> QD-11753 Add Ruby project recognition and native support

- tooling/resources.json
> :arrow_up: Update publisher to 3.0.7

- tooling/resources.json
> :arrow_up: QD-11903 Upgrade config-loader-cli.jar

- core/startup/installers.go
- core/startup/releases.go
- platform/utils/utils.go
- tooling/scripts/download-resource.go
> :brics: QD-12017 Add optional auth for downloading linter distribution

- README.md
- platform/cmd/scan_options.go
- platform/commoncontext/analyzer_options_test.go
- platform/commoncontext/compute.go
> :bricks: QD-10741 Update README.md. Fix minor typos.

- cmd/cmd_test.go
- core/startup/installers_test.go
- core/startup/releases_test.go
- platform/commoncontext/analyzer_options_test.go
- platform/product/product.go
> QD-12104 bump eap version to 252

- core/startup/installers_test.go
> QD-12099 Compilation fix

- platform/commoncontext/compute.go
- platform/run.go
> :bricks: QD-12311 3rd party linter implementation should not depend on QODANA_DIST
